### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by JulianKropp** [JulianKropp/stream_pipeline#1]
![pipeline](https://github.com/user-attachments/assets/290ddddc-7210-40d3-82bb-755094471cd8)

- [x] Module Pipeline
- [x] ProcessingManager
- [x] Module
- [x] ExecutionModule
- [x] ConditionModule
- [x] CombinationModule
- [x] Worker 0 = SEQEUENCE mode but with parrallel modules the order can be wrong. So ORDER_BY_SEQUENCE still has to work
- [x] Each Module adds it self to the DataPackage
- [x] Add DataPackage
- [x] Add support dynamic module updates
- [x] #4
- [x] #21
- [ ] #7
- [x] #6
- [x] #17
- [ ] #2 
- [ ] #12

## Issues
- [x] On error DP exits with "running": "True"
- [x] Improve gRPC to DP mapping by sending the id of the module
- [x] #24
- [x]  FIRST_WINS: If a DP with an error races an DP with no error. The DP with no error will be a OUTDATED. (Fixed 5750f37840dce3aafe331605a56ad4b051b0b556)
- [x] DP with status exit or error will be callbacked later if using mode ORDER_BY_SEQUENCE or FIRST_WINS. They first have to wait (Fixed 5750f37840dce3aafe331605a56ad4b051b0b556)
- [x] #26 (will not implement this)
- [ ] External Module doesnt know the difference between different pipelines and pipeline instances. It just do stuff. So It has to create an own object for each instance which wants to communicate with. And it needs a timeout which deletes this module object if it exists longer then x.

## Future plans:
- [ ] #5
- [ ] #8
- [ ] #9
- [ ] #3
- [x] Scaling vertical
- [ ] Webside for Live view of the pipline and live edething (like order or adding/removing modules)
- [ ] More Module Options (Queue mode. Oldest, newest, max=10)
- [ ] PupSub between modules phases, controllers. Or a module can send data to an early module which then processes data differently
- [ ] If a DP is faster and outhers are already processing. Stop them after a module is finished by setting the DP.status to outdated. New status RUNNING_OUTDATED. For tha add to OrderTracker self._processing_data_packages to set all older DPs to RUNNING_OUTDATED
