### ISSUE TITLE
Prometeus + DataPackage Metrics

### ISSUE THREAD

**Issue by JulianKropp** [JulianKropp/stream_pipeline#4]
# TODO

## DataPackage: Pipeline
- [x] `start_time`
- [x] `end_time`
- [x] `total_time`

## DataPackage: Controller
- [x] `start_time`
- [x] `end_time`
- [x] `input_waiting_time`
- [x] `output_waiting_time`
- [x] `total_time`

## DataPackage: Phase
- [x] `start_time`
- [x] `end_time`
- [x] `total_time`

## DataPackage: Modul
- [x] `start_time`
- [x] `end_time`
- [x] `waiting_time`
- [x] `total_time`

## Prometheus Matrics: Pipeline
- [x] `pipeline_input_flowrate` Counter
- [x] `pipeline_output_flowrate` Counter
- [x] `pipeline_exit_flowrate` Counter
- [x] `pipeline_overflow_flowrate` Counter
- [x] `pipeline_outdated_flowrate` Counter
- [x] `pipeline_error_flowrate` Counter
- [x] `pipeline_success_time` Summary
- [x] `pipeline_exit_time` Summary
- [x] `pipeline_overflow_time` Summary
- [x] `pipeline_outdated_time` Summary
- [x] `pipeline_error_time` Summary
- [x] `pipeline_processing_counter` Gauge

## Prometheus Matrics: Controller
- [x] `controller_input_flowrate` Counter
- [x] `controller_output_flowrate` Counter
- [x] `controller_exit_flowrate` Counter
- [x] `controller_overflow_flowrate` Counter
- [x] `controller_error_flowrate` Counter
- [x] `controller_outdated_flowrate` Counter
- [x] `controller_input_waiting_time` Summary
- [x] `controller_output_waiting_time` Summary
- [x] `controller_success_time` Summary
- [x] `controller_exit_time` Summary
- [x] `controller_overflow_time` Summary
- [x] `controller_outdated_time` Summary
- [x] `controller_error_time` Summary
- [x] `controller_input_waiting_counter` Gauge
- [x] `controller_output_waiting_counter` Gauge
- [x] `controller_processing_counter` Gauge

## Prometheus Matrics: Phase
- [x] `phase_input_flowrate` Counter
- [x] `phase_output_flowrate` Counter
- [x] `phase_exit_flowrate` Counter
- [x] `phase_error_flowrate` Counter
- [x] `phase_success_time` Summary
- [x] `phase_exit_time` Summary
- [x] `phase_error_time` Summary
- [x] `phase_processing_counter` Gauge

## Prometheus Matrics: Module
- [x] `module_input_flowrate` Counter
- [x] `module_output_flowrate` Counter
- [x] `module_exit_flowrate` Counter
- [x] `module_error_flowrate` Counter
- [x] `module_waiting_time` Summary
- [x] `module_success_time` Summary
- [x] `module_exit_time` Summary
- [x] `module_error_time` Summary
- [x] `module_waiting_counter` Gauge
- [x] `module_processing_counter` Gauge
